# Generated by Django 4.0.6 on 2023-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0002_rename_is_active_driver_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_driver',
        ),
    ]
