# Generated by Django 4.0.6 on 2023-02-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0003_remove_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='find_daikou.driver'),
        ),
    ]
