# Generated by Django 4.0.6 on 2023-03-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0005_alter_driver_latitude_alter_driver_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.TextField(default='Awaiting driver...'),
        ),
    ]
