# Generated by Django 4.0.6 on 2023-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0011_remove_order_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
