# Generated by Django 4.0.6 on 2023-03-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0012_order_eta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='saved_payment_info',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_account_info',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
    ]
