# Generated by Django 4.0.6 on 2023-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_daikou', '0013_remove_customer_saved_payment_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='101', max_length=32),
            preserve_default=False,
        ),
    ]
